name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    # - name: flake8로 린트
    #   run: |
    #     pip install flake8
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: DockerHub에 로그인
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Docker 이미지 빌드
      run: docker build --f accident_detection
      #run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/accident_detection

    - name: Docker 이미지 푸시
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/accident_detection

    - name: AWS EC2에 배포
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/accident_detection
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)
          docker run -d -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/accident_detection
