version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app

  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]

  backend:
    image: your-backend-image
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    command: ["java", "-jar", "/app/your-backend.jar"]
